<?php

namespace AppBundle\Repository;

/**
 * CommentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentarioRepository extends \Doctrine\ORM\EntityRepository
{
}
