<?php

namespace AppBundle\Repository;


/**
 * TemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByTitle()
        {
            return $this->getEntityManager()
                ->createQuery(
                    'SELECT t FROM AppBundle:Tema t ORDER BY t.titulo ASC'
                )
                ->getResult();
        }

}
